name: Run nightly fuzzer jobs

on:
  # TODO: remove
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  erasure-coding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources & submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Install minimal stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install honggfuzz deps
        run: sudo apt-get install --no-install-recommends binutils-dev libunwind8-dev

      - name: Install honggfuzz
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: honggfuzz --version "0.5.54"

      - name: Run fuzzer
        working-directory: ./erasure-coding/fuzzer
        shell: bash
        run: not timeout 5h cargo hfuzz run round_trip

