name: Run nightly fuzzer jobs

on:
  # TODO: remove
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  erasure-coding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources & submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Install minimal stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install honggfuzz deps
        run: sudo apt-get install --no-install-recommends binutils-dev libunwind8-dev

      - name: Install honggfuzz
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: honggfuzz --version "0.5.54"

      - name: Build fuzzer binaries
        working-directory: ./erasure-coding/fuzzer
        run: cargo hfuzz build

      - name: Run fuzzer
        working-directory: ./erasure-coding/fuzzer
        shell: bash
        run: |
          status="$(timeout --signal INT 20s cargo hfuzz run round_trip)"
          if [ $status -eq 0 ]; then
            echo "Found a panic!"
            # TODO: provide Minimal Reproducible Input
            exit 1
          else
            echo "Didn't find any problem in 5 hours of fuzzing"
            exit 0
          fi

